# Site settings
title: MFC Bricklaying
email: micah@mfcbricklaying.com.au
contact_number: "0423458631"
description: >
  Copyright (C) 2015 - MFC Bricklaying
baseurl: ""
url: "http://mfcbricklaying.github.io"
twitter_username: mfcbricklaying
facebook_username: MfcBricklaying

# Build settings
markdown: kramdown

gems:
  - jekyll-redirect-from
